### ISSUE TITLE
Timestamps before Unix Epoch: is this a Git or a Github limitation?

### ISSUE THREAD

**Issue by julien-c** [steeve/france.code-civil#22]
Hey @steeve,

Commits before Jan. 1 1970 are capped at that date. Is this a Git limitation (will be hard to fix) or a Github frontend one? (could be fixed easily)

Cheers!

**Comment by Chouchen** [comment]
As said [here](https://github.com/steeve/france.code-civil/blob/master/README.md#note-technique) : 

> Note technique
> 
> Les dates Git étant basées sur l'epoch Unix (01/01/1970), les changements avant cette date sont tous datés au 01/01/1970, avec secondes incrémentales; Le message du commit donne la vraie date.

It's a Git limitation.

**Comment by julien-c** [comment]
I see, thanks!
