### ISSUE TITLE
Comment suivre le détails des modifs via RSS ?

### ISSUE THREAD

**Issue by nivhg** [steeve/france.code-civil#32]
Merci pour le projet, très sympa.

Par contre, le flux RSS de github ne permet de ne voir que le titre du commit (soit un numéro de loi dont je n'ai aucune idée du sujet !!!), le contenu du RSS est juste un rappel du titre. Une idée de comment on peut voir le détails des modifs en RSS ?
Ou sinon, qu'il y ai au moins le sujet de la loi dans le titre du commit !

Merci d'avance
Vincent

**Comment by Uelb** [comment]
Related to #34

**Comment by nivhg** [comment]
Merci, je ne l'avais pas vu !
