### ISSUE TITLE
Crawler mon bô crawler ^^

### ISSUE THREAD

**Issue by merlindorin** [steeve/france.code-civil#37]
Salut tout le monde,
super initiative :), d'ailleurs on pourrait avoir des branches pour les discussions en cours qui une fois choisie sont mergé sur le master :).

Plus sérieusement, serait-il possible d'avoir accès au Crawler? je ne pense pas qu'il soit bien compliqué mais surtout cela permettrait à tout le monde de pouvoir le vérifier et ainsi s'assurer qu'il n'y a pas de biais voir s'il est possible de l'améliorer. On parle de loi et aujourd'hui ce projet intéresse beaucoup les g33ks avec le cerveau branché sur github ^^. Mais d'autres personnes pourraient être intéressé et il pourrait par exemple y avoir des services autour de ce repository, mais il est nécessaire de "valider" le crawler.

Voiloù ;)

**Comment by MGaetan89** [comment]
Déjà demandé dans l'issue #3

**Comment by merlindorin** [comment]
zut, j'ai cherché crawler :/ ok ty
