### ISSUE TITLE
A quand le code du travail ? 

### ISSUE THREAD

**Issue by laurencedorman** [steeve/france.code-civil#44]
Avez-vous déjà eu l'idée de faire ce que tu as fait avec le code civil mais avec le code du travail? Si c'était envisageable j'aimerais apporter de l'aide !

**Comment by laurencedorman** [comment]
Ah je n'avais pas vu https://github.com/steeve/france.code-civil/tree/everything/Code%20Du%20Travail

**Comment by yvele** [comment]
@ld0rman Du coup tu peux close la issue 😄
